Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  Excludes:
  - bin/update
  - app/helpers/application_helper.rb
  - app/mailers/application_mailer.rb
  - app/models/application_record.rb
  - config/application.rb
  - test/test_helper.rb
  - bin/setup
  - vendor/bundle/**/*
  - db/seeds.rb
  - config/spring.rb
  - bin/yarn
  - Gemfile
